package enums;

public enum Industry {

	//	FINANCIALS
	BANKS,
	CAPITAL_MARKETS,
	CONSUMER_FINANCE,
	DIVERSIFIED_FINANCIAL_SERVICES,
	INSURANCE,
	MORTGAGE_REITS,
	THRIFTS_MORTGAGE_FINANCE,
	
	//	UTILITIES
	ELECTRIC_UTILITIES,
	GAS_UTILITEIS,
	IND_PWR_RENEWABLE_ELECT_PRODUCERS,
	MULTI_UTILITIES,
	WATER_UTILITIES,
	
	//	CONSUMER_DISCRETIONARY
	AUTO_COMPONENTS,
	AUTOMOBILES,
	DISTRIBUTORS,
	DIVERSIFIED_CONSUMER_SERVICES,
	HOTELS_RESTAURANTS_LEISURE,
	HOUSEHOLD_DURABLES,
	INTERNET_CATALOG_RETAIL,
	LEISURE_PRODUCTS,
	MEDIA,
	MULTILINE_RETAIL,
	SPECIALTY_RETAIL,
	TEXTILES_APPAREL_LUXURY_GOODS,
	
	//	CONSUMER_STAPLES
	BEVERAGES,
	FOOD_STAPLES_RETAILING,
	FOOD_PRODUCTS,
	HOUSEHOLD_PRODUCTS,
	PERSONAL_PRODUCTS,
	TOBACCO,
	
	//	ENERGY
	ENERGY_EQUIPMENT_SERVICES,
	OIL_GAS_CONSUMABLE_FUELS,
	
	//	HEALTHCARE
	BIOTECHNOLOGY,
	HEALTH_CARE_EQUIPMENT_SERVICES,
	HEALTH_CARE_PROVIDERS_SERVICES,
	HEATH_CARE_TECHNOLOGY,
	LIFE_SCIENCES_TOOLS_SERVICES,
	PHARMACEUTICALS,
	
	//	INDUSTRIALS
	AEROSPACE_DEFENSE,
	AIR_FREIGHT_LOGISTICS,
	AIRLINES,
	BUILDING_PRODUCTS,
	COMMERCIAL_SERVICES_SUPPLIES,
	CONSTRUCTION_ENGINEERING,
	ELECTRICAL_EQUIPMENT,
	INDUSTRIAL_CONGLOMERATES,
	MACHINERY,
	MARINE,
	PROFESSIONAL_SERVICES,
	ROADS_RAIL,
	TRADING_COMPANIES_DISTRIBUTORS,
	TRANSPORTATION_INFRASTRUCTURE,
	
	//	INFORMATION TECHNOLOGY
	COMMUNICATIONS_EQUIPMENT,
	ELECTRONIC_EQUIPMENT_INSTRUMENTS_COMPONENTS,
	IT_SERVICES,
	INTERNET_SOFTWARE_SERVICES,
	SEMICONDUCTORS_SEMICONDUCTOR_EQUIPMENT,
	SOFTWARE,
	TECHNOLOGY_HARDWARE_STORAGE_PERIPHERALS,
	
	//	TELECOM
	DIVERSIFIED_TELECOM_SERVICES,
	WIRELESS_TELECOM_SERVICES,
	
	//	MATERIALS
	CHEMICALS,
	CONSTRUCTION_MATERIALS,
	CONTAINERS_PACKAGING,
	METALS_MINING,
	PAPER_FOREST_PRODUCTS,
	
	//	REAL_ESTATE
	EQUITY_REAL_ESTATE_INVESTMENT_TRUSTS,
	REAL_ESTATE_MANAGEMENT_DEVELOPMENT
	
}
