package enums;

public enum Sector {
	FINANCIALS, 
	UTILITIES, 
	CONSUMER_DISCRETIONARY, 
	CONSUMER_STAPLES, 
	ENERGY, 
	HEALTHCARE, 
	INDUSTRIALS,
	TECHNOLOGY,
	TELECOM,
	MATERIALS,
	REAL_ESTATE,
}